[project]
name = "python-dig"
version = "0.1.0"
description = "Learn Python’s more advanced features by tinkering"
readme = "README.md"
authors = [
    { name = "Aviah", email = "aviahl@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
python-dig = "python_dig:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"
